name: 'Terraform Spoke Solution'

on:
  push:
    paths:
      - 'solutions/spoke-solution/**'
      - '.github/workflows/spoke-solution.yml'
    branches:
      - main
  pull_request:
    paths:
      - 'solutions/spoke-solution/**'
      - '.github/workflows/spoke-solution.yml'

jobs:
  terraform:
    name: 'Terraform Spoke Solution'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: solutions/spoke-solution

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
